---

- name: Set hostname
  hostname: name={{ hostname }}
  become: true

- name: Updating package sources information
  apt: update_cache=yes
  become: true

- name: Installing base packages
  apt: state=latest name={{ packages }}
  become: true

- name: Setup Bash profile
  template: src=bash_profile.j2 dest=/home/vagrant/.bash_profile
            owner=vagrant group=vagrant mode=0644

- name: Cloning SourceMod repository
  git: repo=https://github.com/alliedmodders/sourcemod.git
       dest=/home/vagrant/sourcemod
       version={{ sourcemod }}
       depth=1

- name: Cloning AMBuild repository
  git: repo=https://github.com/alliedmodders/ambuild.git
       dest=/home/vagrant/ambuild
       depth=1
  register: ambuild_repo

- name: Installing AMBuild
  command: python3 -m pip install --user /home/vagrant/ambuild
  when: ambuild_repo.changed
