---

- name: Set hostname
  hostname: name={{ hostname }}
  become: true

- name: Updating package sources information
  apt: update_cache=yes
  become: true

- name: Setup Git 2 repository
  apt_repository: repo=ppa:git-core/ppa
  become: true

- name: Setup GCC 4.8 repository
  apt_repository: repo=ppa:ubuntu-toolchain-r/test
  become: true

- name: Setup Clang 3.2 repository
  apt_repository: repo=ppa:kxstudio-team/builds
  become: true

- name: Installing base packages
  apt: state=latest name={{ item }}
  become: true
  with_items:
    - git
    - gcc-4.8
    - g++-4.8
    - clang
    - python3-minimal
    - vim

- name: Cloning SourceMod repository
  git: repo=https://github.com/alliedmodders/sourcemod.git
       dest=/home/vagrant/sourcemod
       version={{ sourcemod }}
