---

- name: Installing Python 2.7
  raw: test -e /usr/bin/python || (apt update -y && apt install -y python-minimal)
  become: true

- name: Set hostname
  hostname: name={{ hostname }}
  become: true

- name: Updating package sources information
  apt: update_cache=yes
  become: true

- name: Installing base packages
  apt: state=latest name={{ item }}
  become: true
  with_items:
    - git
    - gcc
    - g++
    - clang
    - vim

- name: Cloning SourceMod repository
  git: repo=https://github.com/alliedmodders/sourcemod.git
       dest=/home/ubuntu/sourcemod
       version={{ sourcemod }}
